spring:
  application:
    name: Polyclinic_PetProject
  datasource:
    url: jdbc:h2:mem:PolyclinicDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: user
#      password: user