create table patients
(
    age             integer not null,
    id              bigint generated by default as identity,
    contact_details varchar(255),
    full_name       varchar(255),
    gender          varchar(255),
    login           varchar(255),
    password        varchar(255),
    primary key (id)
);
create table appointment_time
(
    id         bigint generated by default as identity,
    doctor_id  bigint,
    patient_id bigint,
    primary key (id)
);
create table bookings
(
    id                  bigint generated by default as identity,
    local_date          date,
    status              enum ('BUSY','CANCELED','FREE'),
    time_enum           enum ('time_1','time_2','time_3','time_4','time_5','time_6','time_7','time_8','time_9'),
    appointment_time_id bigint,
    primary key (id)
);
create table doctor_roles
(
    doctor_id bigint not null,
    roles     enum ('ADMIN','USER')
);
create table patient_roles
(
    patient_id bigint not null,
    roles      enum ('ADMIN','USER')
);