create table patients
(
    age             integer not null,
    id              bigint generated by default as identity,
    contact_details varchar(255),
    full_name       varchar(255),
    gender          varchar(255),
    login           varchar(255),
    password        varchar(255),
    primary key (id)
)
